version: '3'

services:
  mysql_db:
    image: mysql:5.7
    container_name: mysql-aliorshop
    environment:
      - MYSQL_DATABASE=aliorshop
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./tmp/mysql:/var/lib/mysql"
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin-aliorshop
    environment:
      PMA_HOST: mysql_db
    depends_on:
      - mysql_db
    ports:
      - 8080:80
volumes:
  mysql_db:
    external: true